name: my first workflow
on: push
jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
        - name: Wecome message
          run: echo "Wecome to first workflow"
        - name: list files
          run: ls -ltra
        - name: read memory
          run: df -kh

